# Generated by Django 5.2.17 on 2026-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_emailtemplate_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=15),
        ),
    ]
